static:
  file-path: E:/
server:
  port: 3006
token:
  secret: ${SECRET} #token秘钥
cookie:
  name: token #cookie名称
  expiry: 2592000 #tcookie失效时间一个月 60 * 60 * 24 * 30,以秒为单位
app:
  appId: com.play.ai
  appName: ai
  avater-img: /static/user/avater/
  avater-path: E:${app.avater-img}
loggin:
  config: /src/main/resources/logback-spring.xml
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大大小
      max-request-size: 50MB # 请求的最大大小
      location: G:/static/ai/
  token:
    secret: ${SECRET} #token秘钥
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    client:
      type: simple
  jpa:
    show-sql: true
  application:
    name: ai
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/play?characterEncoding=utf-8
    username: root
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5  #初始建立连接数量
    minIdle: 5  #最小连接数量
    maxActive: 20 #最大连接数量
    maxWait: 10000  #获取连接最大等待时间，毫秒
    testOnBorrow: true #申请连接时检测连接是否有效
    testOnReturn: false #归还连接时检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
    minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  data:
    redis:
      host: localhost
      database: 3
      port: 6379
      password:
      timeout: 5000
  elasticsearch:
    uris: http://localhost:9200
    initialize-schema: true
    index-name: chat_vector_index
    dimensions: 1024
    host: 9200
    similarity: cosine
mybatis:
  mapper-locations: classpath:mapper/**/*.xml   # Mapper XML 文件路径
  type-aliases-package: com.player.ai.entity  # 实体类包路径，用于别名自动映射
  configuration:
    use-actual-param-name: true
    mapUnderscoreToCamelCase: true              # 自动映射下划线到驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印 SQL 日志

logging:
  level:
    root: INFO
    com.player.ai: DEBUG  # 你的应用包路径
    dev.langchain4j: DEBUG  # LangChain4J相关日志
    org.springframework.web: DEBUG

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      qwen-model-name: qwen3:8b
      deepseek-model-name: deepseek-r1:8b
      log-requests: true
      log-responses: true
      temperature: 0.3
nomic:
  embedding:
    model-name: nomic-embed-text:latest #mxbai-embed-large:latest # 或其他可用模型
    timeout: 60s